
select * from
(select count(*) as sfmcu from invoiced i1 where i1.sfmcu is null) as sfmcu cross join
(select count(*) as sfco from invoiced i2 where i2.sfco is null) as sfco cross join
(select count(*) as sfrkco from invoiced i3 where i3.sfrkco is null) as sfrkco cross join
(select count(*) as sfdoc from invoiced i4 where i4.sfdoc is null) as sfdoc cross join
(select count(*) as sfdoco from invoiced i5 where i5.sfdoco is null) as sfdoco cross join
(select count(*) as sfdcto from invoiced i6 where i6.sfdcto is null) as sfdcto cross join
(select count(*) as sflnid from invoiced i7 where i7.sflnid is null) as sflnid cross join
(select count(*) as sfsfxo from invoiced i8 where i8.sfsfxo is null) as sfsfxo cross join
(select count(*) as sflnty from invoiced i9 where i9.sflnty is null) as sflnty cross join
(select count(*) as sflntyd from invoiced i10 where i10.sflntyd is null) as sflntyd cross join
(select count(*) as sftrdj from invoiced i11 where i11.sftrdj is null) as sftrdj cross join
(select count(*) as sfdrqj from invoiced i12 where i12.sfdrqj is null) as sfdrqj cross join
(select count(*) as sfaddj from invoiced i13 where i13.sfaddj is null) as sfaddj cross join
(select count(*) as sfivd from invoiced i14 where i14.sfivd is null) as sfivd cross join
(select count(*) as sfitm from invoiced i15 where i15.sfitm is null) as sfitm cross join
(select count(*) as sflitm from invoiced i16 where i16.sflitm is null) as sflitm cross join
(select count(*) as sfdsc1 from invoiced i17 where i17.sfdsc1 is null) as sfdsc1 cross join
(select count(*) as sfdsc2 from invoiced i18 where i18.sfdsc2 is null) as sfdsc2 cross join
(select count(*) as sfrlit from invoiced i19 where i19.sfrlit is null) as sfrlit cross join
(select count(*) as sfktln from invoiced i20 where i20.sfktln is null) as sfktln cross join
(select count(*) as sflttr from invoiced i21 where i21.sflttr is null) as sflttr cross join
(select count(*) as sfnxtr from invoiced i22 where i22.sfnxtr is null) as sfnxtr cross join
(select count(*) as sflprc from invoiced i23 where i23.sflprc is null) as sflprc cross join
(select count(*) as sfuprc from invoiced i24 where i24.sfuprc is null) as sfuprc cross join
(select count(*) as sfaexp from invoiced i25 where i25.sfaexp is null) as sfaexp cross join
(select count(*) as sfasn from invoiced i26 where i26.sfasn is null) as sfasn cross join
(select count(*) as sfprov from invoiced i27 where i27.sfprov is null) as sfprov cross join
(select count(*) as sfuncs from invoiced i28 where i28.sfuncs is null) as sfuncs cross join
(select count(*) as sfecst from invoiced i29 where i29.sfecst is null) as sfecst cross join
(select count(*) as sfuorg from invoiced i30 where i30.sfuorg is null) as sfuorg cross join
(select count(*) as sfsocn from invoiced i31 where i31.sfsocn is null) as sfsocn cross join
(select count(*) as sfuom from invoiced i32 where i32.sfuom is null) as sfuom cross join
(select count(*) as sfsoqs from invoiced i33 where i33.sfsoqs is null) as sfsoqs cross join
(select count(*) as sfitwt from invoiced i34 where i34.sfitwt is null) as sfitwt cross join
(select count(*) as sfsrp1 from invoiced i35 where i35.sfsrp1 is null) as sfsrp1 cross join
(select count(*) as sfsrp1d from invoiced i36 where i36.sfsrp1d is null) as sfsrp1d cross join
(select count(*) as sfsrp2 from invoiced i37 where i37.sfsrp2 is null) as sfsrp2 cross join
(select count(*) as sfsrp2d from invoiced i38 where i38.sfsrp2d is null) as sfsrp2d cross join
(select count(*) as sfsrp3 from invoiced i39 where i39.sfsrp3 is null) as sfsrp3 cross join
(select count(*) as sfsrp3d from invoiced i40 where i40.sfsrp3d is null) as sfsrp3d cross join
(select count(*) as sfsrp4 from invoiced i41 where i41.sfsrp4 is null) as sfsrp4 cross join
(select count(*) as sfsrp4d from invoiced i42 where i42.sfsrp4d is null) as sfsrp4d cross join
(select count(*) as sfsrp5 from invoiced i43 where i43.sfsrp5 is null) as sfsrp5 cross join
(select count(*) as sfsrp5d from invoiced i44 where i44.sfsrp5d is null) as sfsrp5d cross join
(select count(*) as sfprp4 from invoiced i45 where i45.sfprp4 is null) as sfprp4 cross join
(select count(*) as sfprp4d from invoiced i46 where i46.sfprp4d is null) as sfprp4d cross join
(select count(*) as sfshcn from invoiced i47 where i47.sfshcn is null) as sfshcn cross join
(select count(*) as sfshcnd from invoiced i48 where i48.sfshcnd is null) as sfshcnd cross join
(select count(*) as sfuom1 from invoiced i49 where i49.sfuom1 is null) as sfuom1 cross join
(select count(*) as sfbcrc from invoiced i50 where i50.sfbcrc is null) as sfbcrc cross join
(select count(*) as sfpred from invoiced i51 where i51.sfpred is null) as sfpred cross join
(select count(*) as sfuom4 from invoiced i52 where i52.sfuom4 is null) as sfuom4 cross join
(select count(*) as sfprp6 from invoiced i53 where i53.sfprp6 is null) as sfprp6 cross join
(select count(*) as sfprp6d from invoiced i54 where i54.sfprp6d is null) as sfprp6d cross join
(select count(*) as sfprp9 from invoiced i55 where i55.sfprp9 is null) as sfprp9 cross join
(select count(*) as sfprp9d from invoiced i56 where i56.sfprp9d is null) as sfprp9d cross join
(select count(*) as sfsrp9 from invoiced i57 where i57.sfsrp9 is null) as sfsrp9 cross join
(select count(*) as sfsrp9d from invoiced i58 where i58.sfsrp9d is null) as sfsrp9d cross join
(select count(*) as sfac04 from invoiced i59 where i59.sfac04 is null) as sfac04 cross join
(select count(*) as sfsoad from invoiced i60 where i60.sfsoad is null) as sfsoad cross join
(select count(*) as sfsonm from invoiced i61 where i61.sfsonm is null) as sfsonm cross join
(select count(*) as sfsoct from invoiced i62 where i62.sfsoct is null) as sfsoct cross join
(select count(*) as sfsost from invoiced i63 where i63.sfsost is null) as sfsost cross join
(select count(*) as sfsopc from invoiced i64 where i64.sfsopc is null) as sfsopc cross join
(select count(*) as sfsoco from invoiced i65 where i65.sfsoco is null) as sfsoco cross join
(select count(*) as sfshad from invoiced i66 where i66.sfshad is null) as sfshad cross join
(select count(*) as sfshnm from invoiced i67 where i67.sfshnm is null) as sfshnm cross join
(select count(*) as sfshct from invoiced i68 where i68.sfshct is null) as sfshct cross join
(select count(*) as sfshst from invoiced i69 where i69.sfshst is null) as sfshst cross join
(select count(*) as sfshpc from invoiced i70 where i70.sfshpc is null) as sfshpc cross join
(select count(*) as sfshco from invoiced i71 where i71.sfshco is null) as sfshco cross join
(select count(*) as sfacnm from invoiced i72 where i72.sfacnm is null) as sfacnm cross join
(select count(*) as sfacct from invoiced i73 where i73.sfacct is null) as sfacct cross join
(select count(*) as sfacst from invoiced i74 where i74.sfacst is null) as sfacst cross join
(select count(*) as sfacpc from invoiced i75 where i75.sfacpc is null) as sfacpc cross join
(select count(*) as sfacco from invoiced i76 where i76.sfacco is null) as sfacco cross join
(select count(*) as sfacp from invoiced i77 where i77.sfacp is null) as sfacp cross join
(select count(*) as sfot from invoiced i78 where i78.sfot is null) as sfot cross join
(select count(*) as sfsrc from invoiced i79 where i79.sfsrc is null) as sfsrc cross join
(select count(*) as sfcrco from invoiced i80 where i80.sfcrco is null) as sfcrco cross join
(select count(*) as sfautn from invoiced i81 where i81.sfautn is null) as sfautn cross join
(select count(*) as sfftrh from invoiced i82 where i82.sfftrh is null) as sfftrh cross join
(select count(*) as sffrthd from invoiced i83 where i83.sffrthd is null) as sffrthd cross join
(select count(*) as sftxa1 from invoiced i84 where i84.sftxa1 is null) as sftxa1 cross join
(select count(*) as sfhold from invoiced i85 where i85.sfhold is null) as sfhold cross join
(select count(*) as sfholdd from invoiced i86 where i86.sfholdd is null) as sfholdd cross join
(select count(*) as sfcars from invoiced i87 where i87.sfcars is null) as sfcars cross join
(select count(*) as sfvr01 from invoiced i88 where i88.sfvr01 is null) as sfvr01 cross join
(select count(*) as sfvr03 from invoiced i89 where i89.sfvr03 is null) as sfvr03 cross join
(select count(*) as sfvmid from invoiced i90 where i90.sfvmid is null) as sfvmid cross join
(select count(*) as sfvmidd from invoiced i91 where i91.sfvmidd is null) as sfvmidd cross join
(select count(*) as sfzon from invoiced i92 where i92.sfzon is null) as sfzon cross join
(select count(*) as sfzond from invoiced i93 where i93.sfzond is null) as sfzond cross join
(select count(*) as sfaft from invoiced i94 where i94.sfaft is null) as sfaft cross join
(select count(*) as sfmot from invoiced i95 where i95.sfmot is null) as sfmot cross join
(select count(*) as sfmotd from invoiced i96 where i96.sfmotd is null) as sfmotd cross join
(select count(*) as sfmmtl from invoiced i97 where i97.sfmmtl is null) as sfmmtl cross join
(select count(*) as sfscr from invoiced i98 where i98.sfscr is null) as sfscr cross join
(select count(*) as sfmvar from invoiced i99 where i99.sfmvar is null) as sfmvar cross join
(select count(*) as sfmfix from invoiced i100 where i100.sfmfix is null) as sfmfix cross join
(select count(*) as sflvar from invoiced i101 where i101.sflvar is null) as sflvar cross join
(select count(*) as sflfix from invoiced i102 where i102.sflfix is null) as sflfix cross join
(select count(*) as sfsec from invoiced i103 where i103.sfsec is null) as sfsec cross join
(select count(*) as sfdirl from invoiced i104 where i104.sfdirl is null) as sfdirl cross join
(select count(*) as sfmacr from invoiced i105 where i105.sfmacr is null) as sfmacr cross join
(select count(*) as sfslit from invoiced i106 where i106.sfslit is null) as sfslit cross join
(select count(*) as sfd70 from invoiced i107 where i107.sfd70 is null) as sfd70 cross join
(select count(*) as sfd85 from invoiced i108 where i108.sfd85 is null) as sfd85 cross join
(select count(*) as sfd50 from invoiced i109 where i109.sfd50 is null) as sfd50 cross join
(select count(*) as sfd35 from invoiced i110 where i110.sfd35 is null) as sfd35 cross join
(select count(*) as sfwid from invoiced i111 where i111.sfwid is null) as sfwid cross join
(select count(*) as sfhgt from invoiced i112 where i112.sfhgt is null) as sfhgt cross join
(select count(*) as sfsty from invoiced i113 where i113.sfsty is null) as sfsty cross join
(select count(*) as sfoto from invoiced i114 where i114.sfoto is null) as sfoto cross join
(select count(*) as sfwidn from invoiced i115 where i115.sfwidn is null) as sfwidn cross join
(select count(*) as sflact from invoiced i116 where i116.sflact is null) as sflact cross join
(select count(*) as sfhgtn from invoiced i117 where i117.sfhgtn is null) as sfhgtn cross join
(select count(*) as sfacc from invoiced i118 where i118.sfacc is null) as sfacc cross join
(select count(*) as sfgor from invoiced i119 where i119.sfgor is null) as sfgor cross join
(select count(*) as sfhgta from invoiced i120 where i120.sfhgta is null) as sfhgta cross join
(select count(*) as sfmtl from invoiced i121 where i121.sfmtl is null) as sfmtl cross join
(select count(*) as sfplt from invoiced i122 where i122.sfplt is null) as sfplt cross join
(select count(*) as sfsize from invoiced i123 where i123.sfsize is null) as sfsize cross join
(select count(*) as sfprod from invoiced i124 where i124.sfprod is null) as sfprod cross join
(select count(*) as sfmtlg from invoiced i125 where i125.sfmtlg is null) as sfmtlg cross join
(select count(*) as sfnor from invoiced i126 where i126.sfnor is null) as sfnor cross join
(select count(*) as sfpar from invoiced i127 where i127.sfpar is null) as sfpar cross join
(select count(*) as sfbot from invoiced i128 where i128.sfbot is null) as sfbot cross join
(select count(*) as sfprt from invoiced i129 where i129.sfprt is null) as sfprt cross join
(select count(*) as sfopen from invoiced i130 where i130.sfopen is null) as sfopen cross join
(select count(*) as sfgog from invoiced i131 where i131.sfgog is null) as sfgog cross join
(select count(*) as sfcol from invoiced i132 where i132.sfcol is null) as sfcol cross join
(select count(*) as sfcndj from invoiced i133 where i133.sfcndj is null) as sfcndj cross join
(select count(*) as sfstkt from invoiced i134 where i134.sfstkt is null) as sfstkt cross join
(select count(*) as sfglc from invoiced i135 where i135.sfglc is null) as sfglc cross join
(select count(*) as sfglcd from invoiced i136 where i136.sfglcd is null) as sfglcd cross join
(select count(*) as sfptc from invoiced i137 where i137.sfptc is null) as sfptc cross join
(select count(*) as sfptcd from invoiced i138 where i138.sfptcd is null) as sfptcd cross join
(select count(*) as sfglbu from invoiced i139 where i139.sfglbu is null) as sfglbu cross join
(select count(*) as sfglac from invoiced i140 where i140.sfglac is null) as sfglac cross join
(select count(*) as sfglsb from invoiced i141 where i141.sfglsb is null) as sfglsb cross join
(select count(*) as sfac14 from invoiced i142 where i142.sfac14 is null) as sfac14 cross join
(select count(*) as sfac24 from invoiced i143 where i143.sfac24 is null) as sfac24 cross join
(select count(*) as sfuctr from invoiced i144 where i144.sfuctr is null) as sfuctr cross join
(select count(*) as sfqote from invoiced i145 where i145.sfqote is null) as sfqote cross join
(select count(*) as sfadvp from invoiced i146 where i146.sfadvp is null) as sfadvp cross join
(select count(*) as sfover from invoiced i147 where i147.sfover is null) as sfover cross join
(select count(*) as sfmdsc from invoiced i148 where i148.sfmdsc is null) as sfmdsc cross join
(select count(*) as sftdsc from invoiced i149 where i149.sftdsc is null) as sftdsc cross join
(select count(*) as sfpa8 from invoiced i150 where i150.sfpa8 is null) as sfpa8 cross join
(select count(*) as sfprp1 from invoiced i151 where i151.sfprp1 is null) as sfprp1 cross join
(select count(*) as sfprp1d from invoiced i152 where i152.sfprp1d is null) as sfprp1d cross join
(select count(*) as sfprp2 from invoiced i153 where i153.sfprp2 is null) as sfprp2 cross join
(select count(*) as sfprp2d from invoiced i154 where i154.sfprp2d is null) as sfprp2d cross join
(select count(*) as sfprp3 from invoiced i155 where i155.sfprp3 is null) as sfprp3 cross join
(select count(*) as sfprp3d from invoiced i156 where i156.sfprp3d is null) as sfprp3d cross join
(select count(*) as sfsrp7 from invoiced i157 where i157.sfsrp7 is null) as sfsrp7 cross join
(select count(*) as sfsrp7d from invoiced i158 where i158.sfsrp7d is null) as sfsrp7d cross join
(select count(*) as sfshcm from invoiced i159 where i159.sfshcm is null) as sfshcm cross join
(select count(*) as sfshcmd from invoiced i160 where i160.sfshcmd is null) as sfshcmd cross join
(select count(*) as sfta30 from invoiced i161 where i161.sfta30 is null) as sfta30 cross join
(select count(*) as sfta31 from invoiced i162 where i162.sfta31 is null) as sfta31 cross join
(select count(*) as sfta32 from invoiced i163 where i163.sfta32 is null) as sfta32 cross join
(select count(*) as sfta33 from invoiced i164 where i164.sfta33 is null) as sfta33 cross join
(select count(*) as sfupmj from invoiced i165 where i165.sfupmj is null) as sfupmj cross join
(select count(*) as sftday from invoiced i166 where i166.sftday is null) as sftday cross join
(select count(*) as sftorg from invoiced i167 where i167.sftorg is null) as sftorg cross join
(select count(*) as sfdate from invoiced i168 where i168.sfdate is null) as sfdate cross join
(select count(*) as sfsource from invoiced i169 where i169.sfsource is null) as sfsource cross join
(select count(*) as sfprice from invoiced i170 where i170.sfprice is null) as sfprice cross join
(select count(*) as sfimport from invoiced i171 where i171.sfimport is null) as sfimport
